jdbc: 
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://47.104.5.219:3306/xzz_server?useUnicode:true&characterEncoding:UTF-8
  username: root
  password: xzz521sql
  connectionTimeout: 60000

log:
  dir: /home/logs/train_ssm